recipes-bsp: barebox_master: Add missing INTREE_DEFCONFIG for mx6
Without INTREE_DEFCONFIG_mx6 we can not build imx6 machines.

Fixes:
  WARNING: barebox-master-r7.0 do_configure: No defconfig provided.
  This will propably lead to errors.
  ERROR: barebox-master-r7.0 do_configure:

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Jan Remmet <j.remmet@phytec.de>